// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJaisPVRD7XjLeMAroptN3xejKdNAs-E',
    appId: '1:89391164771:web:1634cc75bf26c8778bf756',
    messagingSenderId: '89391164771',
    projectId: 'elara-study',
    authDomain: 'elara-study.firebaseapp.com',
    storageBucket: 'elara-study.firebasestorage.app',
    measurementId: 'G-5TG4HEQF79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDJ1I0Ot_jSKvkqY6fGhCy5_cO6bRuSLo',
    appId: '1:89391164771:android:240ade2016ab98b18bf756',
    messagingSenderId: '89391164771',
    projectId: 'elara-study',
    storageBucket: 'elara-study.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPmq5L5-xCxtljujzWzd90fx0zTuj9QcA',
    appId: '1:89391164771:ios:a380a78b53676ea68bf756',
    messagingSenderId: '89391164771',
    projectId: 'elara-study',
    storageBucket: 'elara-study.firebasestorage.app',
    iosBundleId: 'com.example.elara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPmq5L5-xCxtljujzWzd90fx0zTuj9QcA',
    appId: '1:89391164771:ios:a380a78b53676ea68bf756',
    messagingSenderId: '89391164771',
    projectId: 'elara-study',
    storageBucket: 'elara-study.firebasestorage.app',
    iosBundleId: 'com.example.elara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPJaisPVRD7XjLeMAroptN3xejKdNAs-E',
    appId: '1:89391164771:web:fff554aaaa3cab568bf756',
    messagingSenderId: '89391164771',
    projectId: 'elara-study',
    authDomain: 'elara-study.firebaseapp.com',
    storageBucket: 'elara-study.firebasestorage.app',
    measurementId: 'G-DLDXPBF1R5',
  );
}
